[global]
error_log = /dev/stderr
daemonize = no
[gw]
pool.type = gateway
user = 65534
group = 65534
listen = 0.0.0.0:9001
chdir = /www
http.route[www] = /
[www]
pool.type = fastcgi
user = 65534
group = 65534
listen = 0.0.0.0:9000
pm = static
pm.max_children = 2
chdir = /www
